CREATE TABLE produto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome_produto VARCHAR(255),
   unidade_medida VARCHAR(255),
   precounit BIGINT NOT NULL,
   customer_id BIGINT,
   CONSTRAINT pk_produto PRIMARY KEY (id)
);

ALTER TABLE produto ADD CONSTRAINT FK_PRODUTO_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);